//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaHorarios.Server.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComposicaoHorario
    {
        public int CodigoComposicaoHorario { get; set; }
    
        public virtual ComposicaoCurso ComposicaoCurso { get; set; }
        public virtual Horario Horario { get; set; }
    }
}
