//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaHorarios.Server.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Horario()
        {
            this.ComposicoesHorario = new HashSet<ComposicaoHorario>();
        }
    
        public int CodigoHorario { get; set; }
        public System.TimeSpan HoraInicial { get; set; }
        public System.TimeSpan HoraFinal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComposicaoHorario> ComposicoesHorario { get; set; }
        public virtual DiaSemana DiaSemana { get; set; }
        public virtual Periodo Periodo { get; set; }
    }
}
