//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaHorarios.Server.DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SistemaHorariosEntities : DbContext
    {
        public SistemaHorariosEntities()
            : base("name=SistemaHorariosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ComposicaoCurso> ComposicoesCurso { get; set; }
        public virtual DbSet<ComposicaoHorario> ComposicoesHorario { get; set; }
        public virtual DbSet<Curso> Cursos { get; set; }
        public virtual DbSet<Horario> Horarios { get; set; }
        public virtual DbSet<Materia> Materias { get; set; }
        public virtual DbSet<Periodo> Periodos { get; set; }
        public virtual DbSet<Professor> Professores { get; set; }
        public virtual DbSet<Semestre> Semestres { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<NivelAcesso> NiveisAcesso { get; set; }
        public virtual DbSet<DiaSemana> DiasSemana { get; set; }
    }
}
