//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaHorarios.Client.Model.SistemaHorariosService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SistemaHorariosService.ISistemaHorariosService")]
    public interface ISistemaHorariosService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarCursos", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarCursosResponse")]
        SistemaHorarios.Contracts.ConsultarCursos.ConsultarCursosResponse ConsultarCursos(SistemaHorarios.Contracts.ConsultarCursos.ConsultarCursosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarCursos", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarCursosResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarCursos.ConsultarCursosResponse> ConsultarCursosAsync(SistemaHorarios.Contracts.ConsultarCursos.ConsultarCursosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarDiasSemana", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarDiasSemanaResponse")]
        SistemaHorarios.Contracts.ConsultarDiasSemana.ConsultarDiasSemanaResponse ConsultarDiasSemana(SistemaHorarios.Contracts.ConsultarDiasSemana.ConsultarDiasSemanaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarDiasSemana", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarDiasSemanaResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarDiasSemana.ConsultarDiasSemanaResponse> ConsultarDiasSemanaAsync(SistemaHorarios.Contracts.ConsultarDiasSemana.ConsultarDiasSemanaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarHorarios", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarHorariosResponse")]
        SistemaHorarios.Contracts.ConsultarHorarios.ConsultarHorariosResponse ConsultarHorarios(SistemaHorarios.Contracts.ConsultarHorarios.ConsultarHorariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarHorarios", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarHorariosResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarHorarios.ConsultarHorariosResponse> ConsultarHorariosAsync(SistemaHorarios.Contracts.ConsultarHorarios.ConsultarHorariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarMaterias", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarMateriasResponse")]
        SistemaHorarios.Contracts.ConsultarMaterias.ConsultarMateriasResponse ConsultarMaterias(SistemaHorarios.Contracts.ConsultarMaterias.ConsultarMateriasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarMaterias", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarMateriasResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarMaterias.ConsultarMateriasResponse> ConsultarMateriasAsync(SistemaHorarios.Contracts.ConsultarMaterias.ConsultarMateriasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarPeriodos", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarPeriodosResponse")]
        SistemaHorarios.Contracts.ConsultarPeriodos.ConsultarPeriodosResponse ConsultarPeriodos(SistemaHorarios.Contracts.ConsultarPeriodos.ConsultarPeriodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarPeriodos", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarPeriodosResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarPeriodos.ConsultarPeriodosResponse> ConsultarPeriodosAsync(SistemaHorarios.Contracts.ConsultarPeriodos.ConsultarPeriodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarProfessores", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarProfessoresResponse")]
        SistemaHorarios.Contracts.ConsultarProfessores.ConsultarProfessoresResponse ConsultarProfessores(SistemaHorarios.Contracts.ConsultarProfessores.ConsultarProfessoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarProfessores", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarProfessoresResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarProfessores.ConsultarProfessoresResponse> ConsultarProfessoresAsync(SistemaHorarios.Contracts.ConsultarProfessores.ConsultarProfessoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarSemestres", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarSemestresResponse")]
        SistemaHorarios.Contracts.ConsultarSemestres.ConsultarSemestresResponse ConsultarSemestres(SistemaHorarios.Contracts.ConsultarSemestres.ConsultarSemestresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarSemestres", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarSemestresResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarSemestres.ConsultarSemestresResponse> ConsultarSemestresAsync(SistemaHorarios.Contracts.ConsultarSemestres.ConsultarSemestresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarUsuarios", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarUsuariosResponse")]
        SistemaHorarios.Contracts.ConsultarUsuarios.ConsultarUsuariosResponse ConsultarUsuarios(SistemaHorarios.Contracts.ConsultarUsuarios.ConsultarUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarUsuarios", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarUsuariosResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarUsuarios.ConsultarUsuariosResponse> ConsultarUsuariosAsync(SistemaHorarios.Contracts.ConsultarUsuarios.ConsultarUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/CadastrarComposicaoCurso", ReplyAction="http://tempuri.org/ISistemaHorariosService/CadastrarComposicaoCursoResponse")]
        SistemaHorarios.Contracts.CadastrarComposicaoCurso.CadastrarComposicaoCursoResponse CadastrarComposicaoCurso(SistemaHorarios.Contracts.CadastrarComposicaoCurso.CadastrarComposicaoCursoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/CadastrarComposicaoCurso", ReplyAction="http://tempuri.org/ISistemaHorariosService/CadastrarComposicaoCursoResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.CadastrarComposicaoCurso.CadastrarComposicaoCursoResponse> CadastrarComposicaoCursoAsync(SistemaHorarios.Contracts.CadastrarComposicaoCurso.CadastrarComposicaoCursoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/CadastrarComposicoesHorario", ReplyAction="http://tempuri.org/ISistemaHorariosService/CadastrarComposicoesHorarioResponse")]
        SistemaHorarios.Contracts.CadastrarComposicoesHorario.CadastrarComposicoesHorarioResponse CadastrarComposicoesHorario(SistemaHorarios.Contracts.CadastrarComposicoesHorario.CadastrarComposicoesHorarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/CadastrarComposicoesHorario", ReplyAction="http://tempuri.org/ISistemaHorariosService/CadastrarComposicoesHorarioResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.CadastrarComposicoesHorario.CadastrarComposicoesHorarioResponse> CadastrarComposicoesHorarioAsync(SistemaHorarios.Contracts.CadastrarComposicoesHorario.CadastrarComposicoesHorarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/CadastrarCursos", ReplyAction="http://tempuri.org/ISistemaHorariosService/CadastrarCursosResponse")]
        SistemaHorarios.Contracts.CadastrarCursos.CadastrarCursosResponse CadastrarCursos(SistemaHorarios.Contracts.CadastrarCursos.CadastrarCursosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/CadastrarCursos", ReplyAction="http://tempuri.org/ISistemaHorariosService/CadastrarCursosResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.CadastrarCursos.CadastrarCursosResponse> CadastrarCursosAsync(SistemaHorarios.Contracts.CadastrarCursos.CadastrarCursosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/CadastrarHorarios", ReplyAction="http://tempuri.org/ISistemaHorariosService/CadastrarHorariosResponse")]
        SistemaHorarios.Contracts.CadastrarHorarios.CadastrarHorariosResponse CadastrarHorarios(SistemaHorarios.Contracts.CadastrarHorarios.CadastrarHorariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/CadastrarHorarios", ReplyAction="http://tempuri.org/ISistemaHorariosService/CadastrarHorariosResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.CadastrarHorarios.CadastrarHorariosResponse> CadastrarHorariosAsync(SistemaHorarios.Contracts.CadastrarHorarios.CadastrarHorariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/CadastrarMaterias", ReplyAction="http://tempuri.org/ISistemaHorariosService/CadastrarMateriasResponse")]
        SistemaHorarios.Contracts.CadastrarMaterias.CadastrarMateriasResponse CadastrarMaterias(SistemaHorarios.Contracts.CadastrarMaterias.CadastrarMateriasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/CadastrarMaterias", ReplyAction="http://tempuri.org/ISistemaHorariosService/CadastrarMateriasResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.CadastrarMaterias.CadastrarMateriasResponse> CadastrarMateriasAsync(SistemaHorarios.Contracts.CadastrarMaterias.CadastrarMateriasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/CadastrarNiveisAcesso", ReplyAction="http://tempuri.org/ISistemaHorariosService/CadastrarNiveisAcessoResponse")]
        SistemaHorarios.Contracts.CadastrarNiveisAcesso.CadastrarNiveisAcessoResponse CadastrarNiveisAcesso(SistemaHorarios.Contracts.CadastrarNiveisAcesso.CadastrarNiveisAcessoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/CadastrarNiveisAcesso", ReplyAction="http://tempuri.org/ISistemaHorariosService/CadastrarNiveisAcessoResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.CadastrarNiveisAcesso.CadastrarNiveisAcessoResponse> CadastrarNiveisAcessoAsync(SistemaHorarios.Contracts.CadastrarNiveisAcesso.CadastrarNiveisAcessoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/CadastrarPeriodos", ReplyAction="http://tempuri.org/ISistemaHorariosService/CadastrarPeriodosResponse")]
        SistemaHorarios.Contracts.CadastrarPeriodos.CadastrarPeriodosResponse CadastrarPeriodos(SistemaHorarios.Contracts.CadastrarPeriodos.CadastrarPeriodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/CadastrarPeriodos", ReplyAction="http://tempuri.org/ISistemaHorariosService/CadastrarPeriodosResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.CadastrarPeriodos.CadastrarPeriodosResponse> CadastrarPeriodosAsync(SistemaHorarios.Contracts.CadastrarPeriodos.CadastrarPeriodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/CadastrarProfessores", ReplyAction="http://tempuri.org/ISistemaHorariosService/CadastrarProfessoresResponse")]
        SistemaHorarios.Contracts.CadastrarProfessores.CadastrarProfessoresResponse CadastrarProfessores(SistemaHorarios.Contracts.CadastrarProfessores.CadastrarProfessoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/CadastrarProfessores", ReplyAction="http://tempuri.org/ISistemaHorariosService/CadastrarProfessoresResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.CadastrarProfessores.CadastrarProfessoresResponse> CadastrarProfessoresAsync(SistemaHorarios.Contracts.CadastrarProfessores.CadastrarProfessoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/CadastrarSemestres", ReplyAction="http://tempuri.org/ISistemaHorariosService/CadastrarSemestresResponse")]
        SistemaHorarios.Contracts.CadastrarSemestres.CadastrarSemestresResponse CadastrarSemestres(SistemaHorarios.Contracts.CadastrarSemestres.CadastrarSemestresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/CadastrarSemestres", ReplyAction="http://tempuri.org/ISistemaHorariosService/CadastrarSemestresResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.CadastrarSemestres.CadastrarSemestresResponse> CadastrarSemestresAsync(SistemaHorarios.Contracts.CadastrarSemestres.CadastrarSemestresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/CadastrarUsuarios", ReplyAction="http://tempuri.org/ISistemaHorariosService/CadastrarUsuariosResponse")]
        SistemaHorarios.Contracts.CadastrarUsuarios.CadastrarUsuariosResponse CadastrarUsuarios(SistemaHorarios.Contracts.CadastrarUsuarios.CadastrarUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/CadastrarUsuarios", ReplyAction="http://tempuri.org/ISistemaHorariosService/CadastrarUsuariosResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.CadastrarUsuarios.CadastrarUsuariosResponse> CadastrarUsuariosAsync(SistemaHorarios.Contracts.CadastrarUsuarios.CadastrarUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarComposicoesCurso", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarComposicoesCursoResponse")]
        SistemaHorarios.Contracts.ConsultarComposicoesCurso.ConsultarComposicoesCursoResponse ConsultarComposicoesCurso(SistemaHorarios.Contracts.ConsultarComposicoesCurso.ConsultarComposicoesCursoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarComposicoesCurso", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarComposicoesCursoResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarComposicoesCurso.ConsultarComposicoesCursoResponse> ConsultarComposicoesCursoAsync(SistemaHorarios.Contracts.ConsultarComposicoesCurso.ConsultarComposicoesCursoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarComposicoesHorario", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarComposicoesHorarioResponse")]
        SistemaHorarios.Contracts.ConsultarComposicoesHorario.ConsultarComposicoesHorarioResponse ConsultarComposicoesHorario(SistemaHorarios.Contracts.ConsultarComposicoesHorario.ConsultarComposicoesHorarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarComposicoesHorario", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarComposicoesHorarioResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarComposicoesHorario.ConsultarComposicoesHorarioResponse> ConsultarComposicoesHorarioAsync(SistemaHorarios.Contracts.ConsultarComposicoesHorario.ConsultarComposicoesHorarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/AtualizarComposicaoCurso", ReplyAction="http://tempuri.org/ISistemaHorariosService/AtualizarComposicaoCursoResponse")]
        SistemaHorarios.Contracts.AtualizarComposicaoCurso.AtualizarComposicaoCursoResponse AtualizarComposicaoCurso(SistemaHorarios.Contracts.AtualizarComposicaoCurso.AtualizarComposicaoCursoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/AtualizarComposicaoCurso", ReplyAction="http://tempuri.org/ISistemaHorariosService/AtualizarComposicaoCursoResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.AtualizarComposicaoCurso.AtualizarComposicaoCursoResponse> AtualizarComposicaoCursoAsync(SistemaHorarios.Contracts.AtualizarComposicaoCurso.AtualizarComposicaoCursoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/AtualizarComposicoesHorario", ReplyAction="http://tempuri.org/ISistemaHorariosService/AtualizarComposicoesHorarioResponse")]
        SistemaHorarios.Contracts.AtualizarComposicoesHorario.AtualizarComposicoesHorarioResponse AtualizarComposicoesHorario(SistemaHorarios.Contracts.AtualizarComposicoesHorario.AtualizarComposicoesHorarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/AtualizarComposicoesHorario", ReplyAction="http://tempuri.org/ISistemaHorariosService/AtualizarComposicoesHorarioResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.AtualizarComposicoesHorario.AtualizarComposicoesHorarioResponse> AtualizarComposicoesHorarioAsync(SistemaHorarios.Contracts.AtualizarComposicoesHorario.AtualizarComposicoesHorarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/AtualizarCursos", ReplyAction="http://tempuri.org/ISistemaHorariosService/AtualizarCursosResponse")]
        SistemaHorarios.Contracts.AtualizarCursos.AtualizarCursosResponse AtualizarCursos(SistemaHorarios.Contracts.AtualizarCursos.AtualizarCursosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/AtualizarCursos", ReplyAction="http://tempuri.org/ISistemaHorariosService/AtualizarCursosResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.AtualizarCursos.AtualizarCursosResponse> AtualizarCursosAsync(SistemaHorarios.Contracts.AtualizarCursos.AtualizarCursosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/AtualizarHorarios", ReplyAction="http://tempuri.org/ISistemaHorariosService/AtualizarHorariosResponse")]
        SistemaHorarios.Contracts.AtualizarHorarios.AtualizarHorariosResponse AtualizarHorarios(SistemaHorarios.Contracts.AtualizarHorarios.AtualizarHorariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/AtualizarHorarios", ReplyAction="http://tempuri.org/ISistemaHorariosService/AtualizarHorariosResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.AtualizarHorarios.AtualizarHorariosResponse> AtualizarHorariosAsync(SistemaHorarios.Contracts.AtualizarHorarios.AtualizarHorariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/AtualizarMaterias", ReplyAction="http://tempuri.org/ISistemaHorariosService/AtualizarMateriasResponse")]
        SistemaHorarios.Contracts.AtualizarMaterias.AtualizarMateriasResponse AtualizarMaterias(SistemaHorarios.Contracts.AtualizarMaterias.AtualizarMateriasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/AtualizarMaterias", ReplyAction="http://tempuri.org/ISistemaHorariosService/AtualizarMateriasResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.AtualizarMaterias.AtualizarMateriasResponse> AtualizarMateriasAsync(SistemaHorarios.Contracts.AtualizarMaterias.AtualizarMateriasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/AtualizarNiveisAcesso", ReplyAction="http://tempuri.org/ISistemaHorariosService/AtualizarNiveisAcessoResponse")]
        SistemaHorarios.Contracts.AtualizarNiveisAcesso.AtualizarNiveisAcessoResponse AtualizarNiveisAcesso(SistemaHorarios.Contracts.AtualizarNiveisAcesso.AtualizarNiveisAcessoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/AtualizarNiveisAcesso", ReplyAction="http://tempuri.org/ISistemaHorariosService/AtualizarNiveisAcessoResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.AtualizarNiveisAcesso.AtualizarNiveisAcessoResponse> AtualizarNiveisAcessoAsync(SistemaHorarios.Contracts.AtualizarNiveisAcesso.AtualizarNiveisAcessoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/AtualizarPeriodos", ReplyAction="http://tempuri.org/ISistemaHorariosService/AtualizarPeriodosResponse")]
        SistemaHorarios.Contracts.AtualizarPeriodos.AtualizarPeriodosResponse AtualizarPeriodos(SistemaHorarios.Contracts.AtualizarPeriodos.AtualizarPeriodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/AtualizarPeriodos", ReplyAction="http://tempuri.org/ISistemaHorariosService/AtualizarPeriodosResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.AtualizarPeriodos.AtualizarPeriodosResponse> AtualizarPeriodosAsync(SistemaHorarios.Contracts.AtualizarPeriodos.AtualizarPeriodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/AtualizarProfessores", ReplyAction="http://tempuri.org/ISistemaHorariosService/AtualizarProfessoresResponse")]
        SistemaHorarios.Contracts.AtualizarProfessores.AtualizarProfessoresResponse AtualizarProfessores(SistemaHorarios.Contracts.AtualizarProfessores.AtualizarProfessoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/AtualizarProfessores", ReplyAction="http://tempuri.org/ISistemaHorariosService/AtualizarProfessoresResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.AtualizarProfessores.AtualizarProfessoresResponse> AtualizarProfessoresAsync(SistemaHorarios.Contracts.AtualizarProfessores.AtualizarProfessoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/AtualizarSemestres", ReplyAction="http://tempuri.org/ISistemaHorariosService/AtualizarSemestresResponse")]
        SistemaHorarios.Contracts.AtualizarSemestres.AtualizarSemestresResponse AtualizarSemestres(SistemaHorarios.Contracts.AtualizarSemestres.AtualizarSemestresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/AtualizarSemestres", ReplyAction="http://tempuri.org/ISistemaHorariosService/AtualizarSemestresResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.AtualizarSemestres.AtualizarSemestresResponse> AtualizarSemestresAsync(SistemaHorarios.Contracts.AtualizarSemestres.AtualizarSemestresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/AtualizarUsuarios", ReplyAction="http://tempuri.org/ISistemaHorariosService/AtualizarUsuariosResponse")]
        SistemaHorarios.Contracts.AtualizarUsuarios.AtualizarUsuariosResponse AtualizarUsuarios(SistemaHorarios.Contracts.AtualizarUsuarios.AtualizarUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/AtualizarUsuarios", ReplyAction="http://tempuri.org/ISistemaHorariosService/AtualizarUsuariosResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.AtualizarUsuarios.AtualizarUsuariosResponse> AtualizarUsuariosAsync(SistemaHorarios.Contracts.AtualizarUsuarios.AtualizarUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/DeletarComposicaoCurso", ReplyAction="http://tempuri.org/ISistemaHorariosService/DeletarComposicaoCursoResponse")]
        SistemaHorarios.Contracts.DeletarComposicaoCurso.DeletarComposicaoCursoResponse DeletarComposicaoCurso(SistemaHorarios.Contracts.DeletarComposicaoCurso.DeletarComposicaoCursoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/DeletarComposicaoCurso", ReplyAction="http://tempuri.org/ISistemaHorariosService/DeletarComposicaoCursoResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.DeletarComposicaoCurso.DeletarComposicaoCursoResponse> DeletarComposicaoCursoAsync(SistemaHorarios.Contracts.DeletarComposicaoCurso.DeletarComposicaoCursoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/DeletarComposicoesHorario", ReplyAction="http://tempuri.org/ISistemaHorariosService/DeletarComposicoesHorarioResponse")]
        SistemaHorarios.Contracts.DeletarComposicoesHorario.DeletarComposicoesHorarioResponse DeletarComposicoesHorario(SistemaHorarios.Contracts.DeletarComposicoesHorario.DeletarComposicoesHorarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/DeletarComposicoesHorario", ReplyAction="http://tempuri.org/ISistemaHorariosService/DeletarComposicoesHorarioResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.DeletarComposicoesHorario.DeletarComposicoesHorarioResponse> DeletarComposicoesHorarioAsync(SistemaHorarios.Contracts.DeletarComposicoesHorario.DeletarComposicoesHorarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/DeletarCursos", ReplyAction="http://tempuri.org/ISistemaHorariosService/DeletarCursosResponse")]
        SistemaHorarios.Contracts.DeletarCursos.DeletarCursosResponse DeletarCursos(SistemaHorarios.Contracts.DeletarCursos.DeletarCursosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/DeletarCursos", ReplyAction="http://tempuri.org/ISistemaHorariosService/DeletarCursosResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.DeletarCursos.DeletarCursosResponse> DeletarCursosAsync(SistemaHorarios.Contracts.DeletarCursos.DeletarCursosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/DeletarHorarios", ReplyAction="http://tempuri.org/ISistemaHorariosService/DeletarHorariosResponse")]
        SistemaHorarios.Contracts.DeletarHorarios.DeletarHorariosResponse DeletarHorarios(SistemaHorarios.Contracts.DeletarHorarios.DeletarHorariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/DeletarHorarios", ReplyAction="http://tempuri.org/ISistemaHorariosService/DeletarHorariosResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.DeletarHorarios.DeletarHorariosResponse> DeletarHorariosAsync(SistemaHorarios.Contracts.DeletarHorarios.DeletarHorariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/DeletarMaterias", ReplyAction="http://tempuri.org/ISistemaHorariosService/DeletarMateriasResponse")]
        SistemaHorarios.Contracts.DeletarMaterias.DeletarMateriasResponse DeletarMaterias(SistemaHorarios.Contracts.DeletarMaterias.DeletarMateriasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/DeletarMaterias", ReplyAction="http://tempuri.org/ISistemaHorariosService/DeletarMateriasResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.DeletarMaterias.DeletarMateriasResponse> DeletarMateriasAsync(SistemaHorarios.Contracts.DeletarMaterias.DeletarMateriasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/DeletarNiveisAcesso", ReplyAction="http://tempuri.org/ISistemaHorariosService/DeletarNiveisAcessoResponse")]
        SistemaHorarios.Contracts.DeletarNiveisAcesso.DeletarNiveisAcessoResponse DeletarNiveisAcesso(SistemaHorarios.Contracts.DeletarNiveisAcesso.DeletarNiveisAcessoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/DeletarNiveisAcesso", ReplyAction="http://tempuri.org/ISistemaHorariosService/DeletarNiveisAcessoResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.DeletarNiveisAcesso.DeletarNiveisAcessoResponse> DeletarNiveisAcessoAsync(SistemaHorarios.Contracts.DeletarNiveisAcesso.DeletarNiveisAcessoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/DeletarPeriodos", ReplyAction="http://tempuri.org/ISistemaHorariosService/DeletarPeriodosResponse")]
        SistemaHorarios.Contracts.DeletarPeriodos.DeletarPeriodosResponse DeletarPeriodos(SistemaHorarios.Contracts.DeletarPeriodos.DeletarPeriodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/DeletarPeriodos", ReplyAction="http://tempuri.org/ISistemaHorariosService/DeletarPeriodosResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.DeletarPeriodos.DeletarPeriodosResponse> DeletarPeriodosAsync(SistemaHorarios.Contracts.DeletarPeriodos.DeletarPeriodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/DeletarProfessores", ReplyAction="http://tempuri.org/ISistemaHorariosService/DeletarProfessoresResponse")]
        SistemaHorarios.Contracts.DeletarProfessores.DeletarProfessoresResponse DeletarProfessores(SistemaHorarios.Contracts.DeletarProfessores.DeletarProfessoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/DeletarProfessores", ReplyAction="http://tempuri.org/ISistemaHorariosService/DeletarProfessoresResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.DeletarProfessores.DeletarProfessoresResponse> DeletarProfessoresAsync(SistemaHorarios.Contracts.DeletarProfessores.DeletarProfessoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/DeletarSemestres", ReplyAction="http://tempuri.org/ISistemaHorariosService/DeletarSemestresResponse")]
        SistemaHorarios.Contracts.DeletarSemestres.DeletarSemestresResponse DeletarSemestres(SistemaHorarios.Contracts.DeletarSemestres.DeletarSemestresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/DeletarSemestres", ReplyAction="http://tempuri.org/ISistemaHorariosService/DeletarSemestresResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.DeletarSemestres.DeletarSemestresResponse> DeletarSemestresAsync(SistemaHorarios.Contracts.DeletarSemestres.DeletarSemestresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/DeletarUsuarios", ReplyAction="http://tempuri.org/ISistemaHorariosService/DeletarUsuariosResponse")]
        SistemaHorarios.Contracts.DeletarUsuarios.DeletarUsuariosResponse DeletarUsuarios(SistemaHorarios.Contracts.DeletarUsuarios.DeletarUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/DeletarUsuarios", ReplyAction="http://tempuri.org/ISistemaHorariosService/DeletarUsuariosResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.DeletarUsuarios.DeletarUsuariosResponse> DeletarUsuariosAsync(SistemaHorarios.Contracts.DeletarUsuarios.DeletarUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarProfessorParam", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarProfessorParamResponse")]
        SistemaHorarios.Contracts.ConsultarProfessorParam.ConsultarProfessorParamResponse ConsultarProfessorParam(SistemaHorarios.Contracts.ConsultarProfessorParam.ConsultarProfessorParamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarProfessorParam", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarProfessorParamResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarProfessorParam.ConsultarProfessorParamResponse> ConsultarProfessorParamAsync(SistemaHorarios.Contracts.ConsultarProfessorParam.ConsultarProfessorParamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarCursoParam", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarCursoParamResponse")]
        SistemaHorarios.Contracts.ConsultarCursoParam.ConsultarCursoParamResponse ConsultarCursoParam(SistemaHorarios.Contracts.ConsultarCursoParam.ConsultarCursoParamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarCursoParam", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarCursoParamResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarCursoParam.ConsultarCursoParamResponse> ConsultarCursoParamAsync(SistemaHorarios.Contracts.ConsultarCursoParam.ConsultarCursoParamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarPeriodoParam", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarPeriodoParamResponse")]
        SistemaHorarios.Contracts.ConsultarPeriodoParam.ConsultarPeriodoParamResponse ConsultarPeriodoParam(SistemaHorarios.Contracts.ConsultarPeriodoParam.ConsultarPeriodoParamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarPeriodoParam", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarPeriodoParamResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarPeriodoParam.ConsultarPeriodoParamResponse> ConsultarPeriodoParamAsync(SistemaHorarios.Contracts.ConsultarPeriodoParam.ConsultarPeriodoParamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarHorarioParam", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarHorarioParamResponse")]
        SistemaHorarios.Contracts.ConsultarHorarioParam.ConsultarHorarioParamResponse ConsultarHorarioParam(SistemaHorarios.Contracts.ConsultarHorarioParam.ConsultarHorarioParamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarHorarioParam", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarHorarioParamResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarHorarioParam.ConsultarHorarioParamResponse> ConsultarHorarioParamAsync(SistemaHorarios.Contracts.ConsultarHorarioParam.ConsultarHorarioParamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarMateriaParam", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarMateriaParamResponse")]
        SistemaHorarios.Contracts.ConsultarMateriaParam.ConsultarMateriaParamResponse ConsultarMateriaParam(SistemaHorarios.Contracts.ConsultarMateriaParam.ConsultarMateriaParamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarMateriaParam", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarMateriaParamResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarMateriaParam.ConsultarMateriaParamResponse> ConsultarMateriaParamAsync(SistemaHorarios.Contracts.ConsultarMateriaParam.ConsultarMateriaParamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarDiaSemanaParam", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarDiaSemanaParamResponse")]
        SistemaHorarios.Contracts.ConsultarDiaSemanaParam.ConsultarDiaSemanaParamResponse ConsultarDiaSemanaParam(SistemaHorarios.Contracts.ConsultarDiaSemanaParam.ConsultarDiaSemanaParamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarDiaSemanaParam", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarDiaSemanaParamResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarDiaSemanaParam.ConsultarDiaSemanaParamResponse> ConsultarDiaSemanaParamAsync(SistemaHorarios.Contracts.ConsultarDiaSemanaParam.ConsultarDiaSemanaParamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarNivelAcessoParam", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarNivelAcessoParamResponse")]
        SistemaHorarios.Contracts.ConsultarNivelAcessoParam.ConsultarNivelAcessoParamResponse ConsultarNivelAcessoParam(SistemaHorarios.Contracts.ConsultarNivelAcessoParam.ConsultarNivelAcessoParamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarNivelAcessoParam", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarNivelAcessoParamResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarNivelAcessoParam.ConsultarNivelAcessoParamResponse> ConsultarNivelAcessoParamAsync(SistemaHorarios.Contracts.ConsultarNivelAcessoParam.ConsultarNivelAcessoParamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarNiveisAcesso", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarNiveisAcessoResponse")]
        SistemaHorarios.Contracts.ConsultarNiveisAcesso.ConsultarNiveisAcessoResponse ConsultarNiveisAcesso(SistemaHorarios.Contracts.ConsultarNiveisAcesso.ConsultarNiveisAcessoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarNiveisAcesso", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarNiveisAcessoResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarNiveisAcesso.ConsultarNiveisAcessoResponse> ConsultarNiveisAcessoAsync(SistemaHorarios.Contracts.ConsultarNiveisAcesso.ConsultarNiveisAcessoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarDiasPeriodos", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarDiasPeriodosResponse")]
        SistemaHorarios.Contracts.ConsultarDiasPeriodos.ConsultarDiasPeriodosResponse ConsultarDiasPeriodos(SistemaHorarios.Contracts.ConsultarDiasPeriodos.ConsultarDiasPeriodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarDiasPeriodos", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarDiasPeriodosResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarDiasPeriodos.ConsultarDiasPeriodosResponse> ConsultarDiasPeriodosAsync(SistemaHorarios.Contracts.ConsultarDiasPeriodos.ConsultarDiasPeriodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarDiasHorarios", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarDiasHorariosResponse")]
        SistemaHorarios.Contracts.ConsultarDiasHorarios.ConsultarDiasHorariosResponse ConsultarDiasHorarios(SistemaHorarios.Contracts.ConsultarDiasHorarios.ConsultarDiasHorariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarDiasHorarios", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarDiasHorariosResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarDiasHorarios.ConsultarDiasHorariosResponse> ConsultarDiasHorariosAsync(SistemaHorarios.Contracts.ConsultarDiasHorarios.ConsultarDiasHorariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarUsuariosParam", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarUsuariosParamResponse")]
        SistemaHorarios.Contracts.ConsultarUsuariosParam.ConsultarUsuariosParamResponse ConsultarUsuariosParam(SistemaHorarios.Contracts.ConsultarUsuariosParam.ConsultarUsuariosParamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarUsuariosParam", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarUsuariosParamResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarUsuariosParam.ConsultarUsuariosParamResponse> ConsultarUsuariosParamAsync(SistemaHorarios.Contracts.ConsultarUsuariosParam.ConsultarUsuariosParamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarUsuariosNiveis", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarUsuariosNiveisResponse")]
        SistemaHorarios.Contracts.ConsultarUsuariosNiveis.ConsultarUsuariosNiveisResponse ConsultarUsuariosNiveis(SistemaHorarios.Contracts.ConsultarUsuariosNiveis.ConsultarUsuariosNiveisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarUsuariosNiveis", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarUsuariosNiveisResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarUsuariosNiveis.ConsultarUsuariosNiveisResponse> ConsultarUsuariosNiveisAsync(SistemaHorarios.Contracts.ConsultarUsuariosNiveis.ConsultarUsuariosNiveisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/AutenticarUsuario", ReplyAction="http://tempuri.org/ISistemaHorariosService/AutenticarUsuarioResponse")]
        SistemaHorarios.Contracts.AutenticarUsuario.AutenticarUsuarioResponse AutenticarUsuario(SistemaHorarios.Contracts.AutenticarUsuario.AutenticarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/AutenticarUsuario", ReplyAction="http://tempuri.org/ISistemaHorariosService/AutenticarUsuarioResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.AutenticarUsuario.AutenticarUsuarioResponse> AutenticarUsuarioAsync(SistemaHorarios.Contracts.AutenticarUsuario.AutenticarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarGrade", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarGradeResponse")]
        SistemaHorarios.Contracts.ConsultarGrade.ConsultarGradeResponse ConsultarGrade(SistemaHorarios.Contracts.ConsultarGrade.ConsultarGradeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarGrade", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarGradeResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarGrade.ConsultarGradeResponse> ConsultarGradeAsync(SistemaHorarios.Contracts.ConsultarGrade.ConsultarGradeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarPeriodosPorCurso", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarPeriodosPorCursoResponse")]
        SistemaHorarios.Contracts.ConsultarPeriodosPorCurso.ConsultarPeriodosPorCursoResponse ConsultarPeriodosPorCurso(SistemaHorarios.Contracts.ConsultarPeriodosPorCurso.ConsultarPeriodosPorCursoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarPeriodosPorCurso", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarPeriodosPorCursoResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarPeriodosPorCurso.ConsultarPeriodosPorCursoResponse> ConsultarPeriodosPorCursoAsync(SistemaHorarios.Contracts.ConsultarPeriodosPorCurso.ConsultarPeriodosPorCursoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarCursosSemestres", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarCursosSemestresResponse")]
        SistemaHorarios.Contracts.ConsultarCursosSemestres.ConsultarCursosSemestresResponse ConsultarCursosSemestres(SistemaHorarios.Contracts.ConsultarCursosSemestres.ConsultarCursosSemestresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarCursosSemestres", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarCursosSemestresResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarCursosSemestres.ConsultarCursosSemestresResponse> ConsultarCursosSemestresAsync(SistemaHorarios.Contracts.ConsultarCursosSemestres.ConsultarCursosSemestresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarCursosPeriodosSemestres", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarCursosPeriodosSemestresRespon" +
            "se")]
        SistemaHorarios.Contracts.ConsultarCursosPeriodosSemestres.ConsultarCursosPeriodosSemestresResponse ConsultarCursosPeriodosSemestres(SistemaHorarios.Contracts.ConsultarCursosPeriodosSemestres.ConsultarCursosPeriodosSemestresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarCursosPeriodosSemestres", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarCursosPeriodosSemestresRespon" +
            "se")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarCursosPeriodosSemestres.ConsultarCursosPeriodosSemestresResponse> ConsultarCursosPeriodosSemestresAsync(SistemaHorarios.Contracts.ConsultarCursosPeriodosSemestres.ConsultarCursosPeriodosSemestresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarParametrosCadastroGrade", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarParametrosCadastroGradeRespon" +
            "se")]
        SistemaHorarios.Contracts.ConsultarParametrosCadastroGrade.ConsultarParametrosCadastroGradeResponse ConsultarParametrosCadastroGrade(SistemaHorarios.Contracts.ConsultarParametrosCadastroGrade.ConsultarParametrosCadastroGradeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/ConsultarParametrosCadastroGrade", ReplyAction="http://tempuri.org/ISistemaHorariosService/ConsultarParametrosCadastroGradeRespon" +
            "se")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarParametrosCadastroGrade.ConsultarParametrosCadastroGradeResponse> ConsultarParametrosCadastroGradeAsync(SistemaHorarios.Contracts.ConsultarParametrosCadastroGrade.ConsultarParametrosCadastroGradeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/CadastrarGrade", ReplyAction="http://tempuri.org/ISistemaHorariosService/CadastrarGradeResponse")]
        SistemaHorarios.Contracts.CadastrarGrade.CadastrarGradeResponse CadastrarGrade(SistemaHorarios.Contracts.CadastrarGrade.CadastrarGradeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaHorariosService/CadastrarGrade", ReplyAction="http://tempuri.org/ISistemaHorariosService/CadastrarGradeResponse")]
        System.Threading.Tasks.Task<SistemaHorarios.Contracts.CadastrarGrade.CadastrarGradeResponse> CadastrarGradeAsync(SistemaHorarios.Contracts.CadastrarGrade.CadastrarGradeRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISistemaHorariosServiceChannel : SistemaHorarios.Client.Model.SistemaHorariosService.ISistemaHorariosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SistemaHorariosServiceClient : System.ServiceModel.ClientBase<SistemaHorarios.Client.Model.SistemaHorariosService.ISistemaHorariosService>, SistemaHorarios.Client.Model.SistemaHorariosService.ISistemaHorariosService {
        
        public SistemaHorariosServiceClient() {
        }
        
        public SistemaHorariosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SistemaHorariosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SistemaHorariosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SistemaHorariosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SistemaHorarios.Contracts.ConsultarCursos.ConsultarCursosResponse ConsultarCursos(SistemaHorarios.Contracts.ConsultarCursos.ConsultarCursosRequest request) {
            return base.Channel.ConsultarCursos(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarCursos.ConsultarCursosResponse> ConsultarCursosAsync(SistemaHorarios.Contracts.ConsultarCursos.ConsultarCursosRequest request) {
            return base.Channel.ConsultarCursosAsync(request);
        }
        
        public SistemaHorarios.Contracts.ConsultarDiasSemana.ConsultarDiasSemanaResponse ConsultarDiasSemana(SistemaHorarios.Contracts.ConsultarDiasSemana.ConsultarDiasSemanaRequest request) {
            return base.Channel.ConsultarDiasSemana(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarDiasSemana.ConsultarDiasSemanaResponse> ConsultarDiasSemanaAsync(SistemaHorarios.Contracts.ConsultarDiasSemana.ConsultarDiasSemanaRequest request) {
            return base.Channel.ConsultarDiasSemanaAsync(request);
        }
        
        public SistemaHorarios.Contracts.ConsultarHorarios.ConsultarHorariosResponse ConsultarHorarios(SistemaHorarios.Contracts.ConsultarHorarios.ConsultarHorariosRequest request) {
            return base.Channel.ConsultarHorarios(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarHorarios.ConsultarHorariosResponse> ConsultarHorariosAsync(SistemaHorarios.Contracts.ConsultarHorarios.ConsultarHorariosRequest request) {
            return base.Channel.ConsultarHorariosAsync(request);
        }
        
        public SistemaHorarios.Contracts.ConsultarMaterias.ConsultarMateriasResponse ConsultarMaterias(SistemaHorarios.Contracts.ConsultarMaterias.ConsultarMateriasRequest request) {
            return base.Channel.ConsultarMaterias(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarMaterias.ConsultarMateriasResponse> ConsultarMateriasAsync(SistemaHorarios.Contracts.ConsultarMaterias.ConsultarMateriasRequest request) {
            return base.Channel.ConsultarMateriasAsync(request);
        }
        
        public SistemaHorarios.Contracts.ConsultarPeriodos.ConsultarPeriodosResponse ConsultarPeriodos(SistemaHorarios.Contracts.ConsultarPeriodos.ConsultarPeriodosRequest request) {
            return base.Channel.ConsultarPeriodos(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarPeriodos.ConsultarPeriodosResponse> ConsultarPeriodosAsync(SistemaHorarios.Contracts.ConsultarPeriodos.ConsultarPeriodosRequest request) {
            return base.Channel.ConsultarPeriodosAsync(request);
        }
        
        public SistemaHorarios.Contracts.ConsultarProfessores.ConsultarProfessoresResponse ConsultarProfessores(SistemaHorarios.Contracts.ConsultarProfessores.ConsultarProfessoresRequest request) {
            return base.Channel.ConsultarProfessores(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarProfessores.ConsultarProfessoresResponse> ConsultarProfessoresAsync(SistemaHorarios.Contracts.ConsultarProfessores.ConsultarProfessoresRequest request) {
            return base.Channel.ConsultarProfessoresAsync(request);
        }
        
        public SistemaHorarios.Contracts.ConsultarSemestres.ConsultarSemestresResponse ConsultarSemestres(SistemaHorarios.Contracts.ConsultarSemestres.ConsultarSemestresRequest request) {
            return base.Channel.ConsultarSemestres(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarSemestres.ConsultarSemestresResponse> ConsultarSemestresAsync(SistemaHorarios.Contracts.ConsultarSemestres.ConsultarSemestresRequest request) {
            return base.Channel.ConsultarSemestresAsync(request);
        }
        
        public SistemaHorarios.Contracts.ConsultarUsuarios.ConsultarUsuariosResponse ConsultarUsuarios(SistemaHorarios.Contracts.ConsultarUsuarios.ConsultarUsuariosRequest request) {
            return base.Channel.ConsultarUsuarios(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarUsuarios.ConsultarUsuariosResponse> ConsultarUsuariosAsync(SistemaHorarios.Contracts.ConsultarUsuarios.ConsultarUsuariosRequest request) {
            return base.Channel.ConsultarUsuariosAsync(request);
        }
        
        public SistemaHorarios.Contracts.CadastrarComposicaoCurso.CadastrarComposicaoCursoResponse CadastrarComposicaoCurso(SistemaHorarios.Contracts.CadastrarComposicaoCurso.CadastrarComposicaoCursoRequest request) {
            return base.Channel.CadastrarComposicaoCurso(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.CadastrarComposicaoCurso.CadastrarComposicaoCursoResponse> CadastrarComposicaoCursoAsync(SistemaHorarios.Contracts.CadastrarComposicaoCurso.CadastrarComposicaoCursoRequest request) {
            return base.Channel.CadastrarComposicaoCursoAsync(request);
        }
        
        public SistemaHorarios.Contracts.CadastrarComposicoesHorario.CadastrarComposicoesHorarioResponse CadastrarComposicoesHorario(SistemaHorarios.Contracts.CadastrarComposicoesHorario.CadastrarComposicoesHorarioRequest request) {
            return base.Channel.CadastrarComposicoesHorario(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.CadastrarComposicoesHorario.CadastrarComposicoesHorarioResponse> CadastrarComposicoesHorarioAsync(SistemaHorarios.Contracts.CadastrarComposicoesHorario.CadastrarComposicoesHorarioRequest request) {
            return base.Channel.CadastrarComposicoesHorarioAsync(request);
        }
        
        public SistemaHorarios.Contracts.CadastrarCursos.CadastrarCursosResponse CadastrarCursos(SistemaHorarios.Contracts.CadastrarCursos.CadastrarCursosRequest request) {
            return base.Channel.CadastrarCursos(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.CadastrarCursos.CadastrarCursosResponse> CadastrarCursosAsync(SistemaHorarios.Contracts.CadastrarCursos.CadastrarCursosRequest request) {
            return base.Channel.CadastrarCursosAsync(request);
        }
        
        public SistemaHorarios.Contracts.CadastrarHorarios.CadastrarHorariosResponse CadastrarHorarios(SistemaHorarios.Contracts.CadastrarHorarios.CadastrarHorariosRequest request) {
            return base.Channel.CadastrarHorarios(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.CadastrarHorarios.CadastrarHorariosResponse> CadastrarHorariosAsync(SistemaHorarios.Contracts.CadastrarHorarios.CadastrarHorariosRequest request) {
            return base.Channel.CadastrarHorariosAsync(request);
        }
        
        public SistemaHorarios.Contracts.CadastrarMaterias.CadastrarMateriasResponse CadastrarMaterias(SistemaHorarios.Contracts.CadastrarMaterias.CadastrarMateriasRequest request) {
            return base.Channel.CadastrarMaterias(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.CadastrarMaterias.CadastrarMateriasResponse> CadastrarMateriasAsync(SistemaHorarios.Contracts.CadastrarMaterias.CadastrarMateriasRequest request) {
            return base.Channel.CadastrarMateriasAsync(request);
        }
        
        public SistemaHorarios.Contracts.CadastrarNiveisAcesso.CadastrarNiveisAcessoResponse CadastrarNiveisAcesso(SistemaHorarios.Contracts.CadastrarNiveisAcesso.CadastrarNiveisAcessoRequest request) {
            return base.Channel.CadastrarNiveisAcesso(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.CadastrarNiveisAcesso.CadastrarNiveisAcessoResponse> CadastrarNiveisAcessoAsync(SistemaHorarios.Contracts.CadastrarNiveisAcesso.CadastrarNiveisAcessoRequest request) {
            return base.Channel.CadastrarNiveisAcessoAsync(request);
        }
        
        public SistemaHorarios.Contracts.CadastrarPeriodos.CadastrarPeriodosResponse CadastrarPeriodos(SistemaHorarios.Contracts.CadastrarPeriodos.CadastrarPeriodosRequest request) {
            return base.Channel.CadastrarPeriodos(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.CadastrarPeriodos.CadastrarPeriodosResponse> CadastrarPeriodosAsync(SistemaHorarios.Contracts.CadastrarPeriodos.CadastrarPeriodosRequest request) {
            return base.Channel.CadastrarPeriodosAsync(request);
        }
        
        public SistemaHorarios.Contracts.CadastrarProfessores.CadastrarProfessoresResponse CadastrarProfessores(SistemaHorarios.Contracts.CadastrarProfessores.CadastrarProfessoresRequest request) {
            return base.Channel.CadastrarProfessores(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.CadastrarProfessores.CadastrarProfessoresResponse> CadastrarProfessoresAsync(SistemaHorarios.Contracts.CadastrarProfessores.CadastrarProfessoresRequest request) {
            return base.Channel.CadastrarProfessoresAsync(request);
        }
        
        public SistemaHorarios.Contracts.CadastrarSemestres.CadastrarSemestresResponse CadastrarSemestres(SistemaHorarios.Contracts.CadastrarSemestres.CadastrarSemestresRequest request) {
            return base.Channel.CadastrarSemestres(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.CadastrarSemestres.CadastrarSemestresResponse> CadastrarSemestresAsync(SistemaHorarios.Contracts.CadastrarSemestres.CadastrarSemestresRequest request) {
            return base.Channel.CadastrarSemestresAsync(request);
        }
        
        public SistemaHorarios.Contracts.CadastrarUsuarios.CadastrarUsuariosResponse CadastrarUsuarios(SistemaHorarios.Contracts.CadastrarUsuarios.CadastrarUsuariosRequest request) {
            return base.Channel.CadastrarUsuarios(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.CadastrarUsuarios.CadastrarUsuariosResponse> CadastrarUsuariosAsync(SistemaHorarios.Contracts.CadastrarUsuarios.CadastrarUsuariosRequest request) {
            return base.Channel.CadastrarUsuariosAsync(request);
        }
        
        public SistemaHorarios.Contracts.ConsultarComposicoesCurso.ConsultarComposicoesCursoResponse ConsultarComposicoesCurso(SistemaHorarios.Contracts.ConsultarComposicoesCurso.ConsultarComposicoesCursoRequest request) {
            return base.Channel.ConsultarComposicoesCurso(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarComposicoesCurso.ConsultarComposicoesCursoResponse> ConsultarComposicoesCursoAsync(SistemaHorarios.Contracts.ConsultarComposicoesCurso.ConsultarComposicoesCursoRequest request) {
            return base.Channel.ConsultarComposicoesCursoAsync(request);
        }
        
        public SistemaHorarios.Contracts.ConsultarComposicoesHorario.ConsultarComposicoesHorarioResponse ConsultarComposicoesHorario(SistemaHorarios.Contracts.ConsultarComposicoesHorario.ConsultarComposicoesHorarioRequest request) {
            return base.Channel.ConsultarComposicoesHorario(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarComposicoesHorario.ConsultarComposicoesHorarioResponse> ConsultarComposicoesHorarioAsync(SistemaHorarios.Contracts.ConsultarComposicoesHorario.ConsultarComposicoesHorarioRequest request) {
            return base.Channel.ConsultarComposicoesHorarioAsync(request);
        }
        
        public SistemaHorarios.Contracts.AtualizarComposicaoCurso.AtualizarComposicaoCursoResponse AtualizarComposicaoCurso(SistemaHorarios.Contracts.AtualizarComposicaoCurso.AtualizarComposicaoCursoRequest request) {
            return base.Channel.AtualizarComposicaoCurso(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.AtualizarComposicaoCurso.AtualizarComposicaoCursoResponse> AtualizarComposicaoCursoAsync(SistemaHorarios.Contracts.AtualizarComposicaoCurso.AtualizarComposicaoCursoRequest request) {
            return base.Channel.AtualizarComposicaoCursoAsync(request);
        }
        
        public SistemaHorarios.Contracts.AtualizarComposicoesHorario.AtualizarComposicoesHorarioResponse AtualizarComposicoesHorario(SistemaHorarios.Contracts.AtualizarComposicoesHorario.AtualizarComposicoesHorarioRequest request) {
            return base.Channel.AtualizarComposicoesHorario(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.AtualizarComposicoesHorario.AtualizarComposicoesHorarioResponse> AtualizarComposicoesHorarioAsync(SistemaHorarios.Contracts.AtualizarComposicoesHorario.AtualizarComposicoesHorarioRequest request) {
            return base.Channel.AtualizarComposicoesHorarioAsync(request);
        }
        
        public SistemaHorarios.Contracts.AtualizarCursos.AtualizarCursosResponse AtualizarCursos(SistemaHorarios.Contracts.AtualizarCursos.AtualizarCursosRequest request) {
            return base.Channel.AtualizarCursos(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.AtualizarCursos.AtualizarCursosResponse> AtualizarCursosAsync(SistemaHorarios.Contracts.AtualizarCursos.AtualizarCursosRequest request) {
            return base.Channel.AtualizarCursosAsync(request);
        }
        
        public SistemaHorarios.Contracts.AtualizarHorarios.AtualizarHorariosResponse AtualizarHorarios(SistemaHorarios.Contracts.AtualizarHorarios.AtualizarHorariosRequest request) {
            return base.Channel.AtualizarHorarios(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.AtualizarHorarios.AtualizarHorariosResponse> AtualizarHorariosAsync(SistemaHorarios.Contracts.AtualizarHorarios.AtualizarHorariosRequest request) {
            return base.Channel.AtualizarHorariosAsync(request);
        }
        
        public SistemaHorarios.Contracts.AtualizarMaterias.AtualizarMateriasResponse AtualizarMaterias(SistemaHorarios.Contracts.AtualizarMaterias.AtualizarMateriasRequest request) {
            return base.Channel.AtualizarMaterias(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.AtualizarMaterias.AtualizarMateriasResponse> AtualizarMateriasAsync(SistemaHorarios.Contracts.AtualizarMaterias.AtualizarMateriasRequest request) {
            return base.Channel.AtualizarMateriasAsync(request);
        }
        
        public SistemaHorarios.Contracts.AtualizarNiveisAcesso.AtualizarNiveisAcessoResponse AtualizarNiveisAcesso(SistemaHorarios.Contracts.AtualizarNiveisAcesso.AtualizarNiveisAcessoRequest request) {
            return base.Channel.AtualizarNiveisAcesso(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.AtualizarNiveisAcesso.AtualizarNiveisAcessoResponse> AtualizarNiveisAcessoAsync(SistemaHorarios.Contracts.AtualizarNiveisAcesso.AtualizarNiveisAcessoRequest request) {
            return base.Channel.AtualizarNiveisAcessoAsync(request);
        }
        
        public SistemaHorarios.Contracts.AtualizarPeriodos.AtualizarPeriodosResponse AtualizarPeriodos(SistemaHorarios.Contracts.AtualizarPeriodos.AtualizarPeriodosRequest request) {
            return base.Channel.AtualizarPeriodos(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.AtualizarPeriodos.AtualizarPeriodosResponse> AtualizarPeriodosAsync(SistemaHorarios.Contracts.AtualizarPeriodos.AtualizarPeriodosRequest request) {
            return base.Channel.AtualizarPeriodosAsync(request);
        }
        
        public SistemaHorarios.Contracts.AtualizarProfessores.AtualizarProfessoresResponse AtualizarProfessores(SistemaHorarios.Contracts.AtualizarProfessores.AtualizarProfessoresRequest request) {
            return base.Channel.AtualizarProfessores(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.AtualizarProfessores.AtualizarProfessoresResponse> AtualizarProfessoresAsync(SistemaHorarios.Contracts.AtualizarProfessores.AtualizarProfessoresRequest request) {
            return base.Channel.AtualizarProfessoresAsync(request);
        }
        
        public SistemaHorarios.Contracts.AtualizarSemestres.AtualizarSemestresResponse AtualizarSemestres(SistemaHorarios.Contracts.AtualizarSemestres.AtualizarSemestresRequest request) {
            return base.Channel.AtualizarSemestres(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.AtualizarSemestres.AtualizarSemestresResponse> AtualizarSemestresAsync(SistemaHorarios.Contracts.AtualizarSemestres.AtualizarSemestresRequest request) {
            return base.Channel.AtualizarSemestresAsync(request);
        }
        
        public SistemaHorarios.Contracts.AtualizarUsuarios.AtualizarUsuariosResponse AtualizarUsuarios(SistemaHorarios.Contracts.AtualizarUsuarios.AtualizarUsuariosRequest request) {
            return base.Channel.AtualizarUsuarios(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.AtualizarUsuarios.AtualizarUsuariosResponse> AtualizarUsuariosAsync(SistemaHorarios.Contracts.AtualizarUsuarios.AtualizarUsuariosRequest request) {
            return base.Channel.AtualizarUsuariosAsync(request);
        }
        
        public SistemaHorarios.Contracts.DeletarComposicaoCurso.DeletarComposicaoCursoResponse DeletarComposicaoCurso(SistemaHorarios.Contracts.DeletarComposicaoCurso.DeletarComposicaoCursoRequest request) {
            return base.Channel.DeletarComposicaoCurso(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.DeletarComposicaoCurso.DeletarComposicaoCursoResponse> DeletarComposicaoCursoAsync(SistemaHorarios.Contracts.DeletarComposicaoCurso.DeletarComposicaoCursoRequest request) {
            return base.Channel.DeletarComposicaoCursoAsync(request);
        }
        
        public SistemaHorarios.Contracts.DeletarComposicoesHorario.DeletarComposicoesHorarioResponse DeletarComposicoesHorario(SistemaHorarios.Contracts.DeletarComposicoesHorario.DeletarComposicoesHorarioRequest request) {
            return base.Channel.DeletarComposicoesHorario(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.DeletarComposicoesHorario.DeletarComposicoesHorarioResponse> DeletarComposicoesHorarioAsync(SistemaHorarios.Contracts.DeletarComposicoesHorario.DeletarComposicoesHorarioRequest request) {
            return base.Channel.DeletarComposicoesHorarioAsync(request);
        }
        
        public SistemaHorarios.Contracts.DeletarCursos.DeletarCursosResponse DeletarCursos(SistemaHorarios.Contracts.DeletarCursos.DeletarCursosRequest request) {
            return base.Channel.DeletarCursos(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.DeletarCursos.DeletarCursosResponse> DeletarCursosAsync(SistemaHorarios.Contracts.DeletarCursos.DeletarCursosRequest request) {
            return base.Channel.DeletarCursosAsync(request);
        }
        
        public SistemaHorarios.Contracts.DeletarHorarios.DeletarHorariosResponse DeletarHorarios(SistemaHorarios.Contracts.DeletarHorarios.DeletarHorariosRequest request) {
            return base.Channel.DeletarHorarios(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.DeletarHorarios.DeletarHorariosResponse> DeletarHorariosAsync(SistemaHorarios.Contracts.DeletarHorarios.DeletarHorariosRequest request) {
            return base.Channel.DeletarHorariosAsync(request);
        }
        
        public SistemaHorarios.Contracts.DeletarMaterias.DeletarMateriasResponse DeletarMaterias(SistemaHorarios.Contracts.DeletarMaterias.DeletarMateriasRequest request) {
            return base.Channel.DeletarMaterias(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.DeletarMaterias.DeletarMateriasResponse> DeletarMateriasAsync(SistemaHorarios.Contracts.DeletarMaterias.DeletarMateriasRequest request) {
            return base.Channel.DeletarMateriasAsync(request);
        }
        
        public SistemaHorarios.Contracts.DeletarNiveisAcesso.DeletarNiveisAcessoResponse DeletarNiveisAcesso(SistemaHorarios.Contracts.DeletarNiveisAcesso.DeletarNiveisAcessoRequest request) {
            return base.Channel.DeletarNiveisAcesso(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.DeletarNiveisAcesso.DeletarNiveisAcessoResponse> DeletarNiveisAcessoAsync(SistemaHorarios.Contracts.DeletarNiveisAcesso.DeletarNiveisAcessoRequest request) {
            return base.Channel.DeletarNiveisAcessoAsync(request);
        }
        
        public SistemaHorarios.Contracts.DeletarPeriodos.DeletarPeriodosResponse DeletarPeriodos(SistemaHorarios.Contracts.DeletarPeriodos.DeletarPeriodosRequest request) {
            return base.Channel.DeletarPeriodos(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.DeletarPeriodos.DeletarPeriodosResponse> DeletarPeriodosAsync(SistemaHorarios.Contracts.DeletarPeriodos.DeletarPeriodosRequest request) {
            return base.Channel.DeletarPeriodosAsync(request);
        }
        
        public SistemaHorarios.Contracts.DeletarProfessores.DeletarProfessoresResponse DeletarProfessores(SistemaHorarios.Contracts.DeletarProfessores.DeletarProfessoresRequest request) {
            return base.Channel.DeletarProfessores(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.DeletarProfessores.DeletarProfessoresResponse> DeletarProfessoresAsync(SistemaHorarios.Contracts.DeletarProfessores.DeletarProfessoresRequest request) {
            return base.Channel.DeletarProfessoresAsync(request);
        }
        
        public SistemaHorarios.Contracts.DeletarSemestres.DeletarSemestresResponse DeletarSemestres(SistemaHorarios.Contracts.DeletarSemestres.DeletarSemestresRequest request) {
            return base.Channel.DeletarSemestres(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.DeletarSemestres.DeletarSemestresResponse> DeletarSemestresAsync(SistemaHorarios.Contracts.DeletarSemestres.DeletarSemestresRequest request) {
            return base.Channel.DeletarSemestresAsync(request);
        }
        
        public SistemaHorarios.Contracts.DeletarUsuarios.DeletarUsuariosResponse DeletarUsuarios(SistemaHorarios.Contracts.DeletarUsuarios.DeletarUsuariosRequest request) {
            return base.Channel.DeletarUsuarios(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.DeletarUsuarios.DeletarUsuariosResponse> DeletarUsuariosAsync(SistemaHorarios.Contracts.DeletarUsuarios.DeletarUsuariosRequest request) {
            return base.Channel.DeletarUsuariosAsync(request);
        }
        
        public SistemaHorarios.Contracts.ConsultarProfessorParam.ConsultarProfessorParamResponse ConsultarProfessorParam(SistemaHorarios.Contracts.ConsultarProfessorParam.ConsultarProfessorParamRequest request) {
            return base.Channel.ConsultarProfessorParam(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarProfessorParam.ConsultarProfessorParamResponse> ConsultarProfessorParamAsync(SistemaHorarios.Contracts.ConsultarProfessorParam.ConsultarProfessorParamRequest request) {
            return base.Channel.ConsultarProfessorParamAsync(request);
        }
        
        public SistemaHorarios.Contracts.ConsultarCursoParam.ConsultarCursoParamResponse ConsultarCursoParam(SistemaHorarios.Contracts.ConsultarCursoParam.ConsultarCursoParamRequest request) {
            return base.Channel.ConsultarCursoParam(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarCursoParam.ConsultarCursoParamResponse> ConsultarCursoParamAsync(SistemaHorarios.Contracts.ConsultarCursoParam.ConsultarCursoParamRequest request) {
            return base.Channel.ConsultarCursoParamAsync(request);
        }
        
        public SistemaHorarios.Contracts.ConsultarPeriodoParam.ConsultarPeriodoParamResponse ConsultarPeriodoParam(SistemaHorarios.Contracts.ConsultarPeriodoParam.ConsultarPeriodoParamRequest request) {
            return base.Channel.ConsultarPeriodoParam(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarPeriodoParam.ConsultarPeriodoParamResponse> ConsultarPeriodoParamAsync(SistemaHorarios.Contracts.ConsultarPeriodoParam.ConsultarPeriodoParamRequest request) {
            return base.Channel.ConsultarPeriodoParamAsync(request);
        }
        
        public SistemaHorarios.Contracts.ConsultarHorarioParam.ConsultarHorarioParamResponse ConsultarHorarioParam(SistemaHorarios.Contracts.ConsultarHorarioParam.ConsultarHorarioParamRequest request) {
            return base.Channel.ConsultarHorarioParam(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarHorarioParam.ConsultarHorarioParamResponse> ConsultarHorarioParamAsync(SistemaHorarios.Contracts.ConsultarHorarioParam.ConsultarHorarioParamRequest request) {
            return base.Channel.ConsultarHorarioParamAsync(request);
        }
        
        public SistemaHorarios.Contracts.ConsultarMateriaParam.ConsultarMateriaParamResponse ConsultarMateriaParam(SistemaHorarios.Contracts.ConsultarMateriaParam.ConsultarMateriaParamRequest request) {
            return base.Channel.ConsultarMateriaParam(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarMateriaParam.ConsultarMateriaParamResponse> ConsultarMateriaParamAsync(SistemaHorarios.Contracts.ConsultarMateriaParam.ConsultarMateriaParamRequest request) {
            return base.Channel.ConsultarMateriaParamAsync(request);
        }
        
        public SistemaHorarios.Contracts.ConsultarDiaSemanaParam.ConsultarDiaSemanaParamResponse ConsultarDiaSemanaParam(SistemaHorarios.Contracts.ConsultarDiaSemanaParam.ConsultarDiaSemanaParamRequest request) {
            return base.Channel.ConsultarDiaSemanaParam(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarDiaSemanaParam.ConsultarDiaSemanaParamResponse> ConsultarDiaSemanaParamAsync(SistemaHorarios.Contracts.ConsultarDiaSemanaParam.ConsultarDiaSemanaParamRequest request) {
            return base.Channel.ConsultarDiaSemanaParamAsync(request);
        }
        
        public SistemaHorarios.Contracts.ConsultarNivelAcessoParam.ConsultarNivelAcessoParamResponse ConsultarNivelAcessoParam(SistemaHorarios.Contracts.ConsultarNivelAcessoParam.ConsultarNivelAcessoParamRequest request) {
            return base.Channel.ConsultarNivelAcessoParam(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarNivelAcessoParam.ConsultarNivelAcessoParamResponse> ConsultarNivelAcessoParamAsync(SistemaHorarios.Contracts.ConsultarNivelAcessoParam.ConsultarNivelAcessoParamRequest request) {
            return base.Channel.ConsultarNivelAcessoParamAsync(request);
        }
        
        public SistemaHorarios.Contracts.ConsultarNiveisAcesso.ConsultarNiveisAcessoResponse ConsultarNiveisAcesso(SistemaHorarios.Contracts.ConsultarNiveisAcesso.ConsultarNiveisAcessoRequest request) {
            return base.Channel.ConsultarNiveisAcesso(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarNiveisAcesso.ConsultarNiveisAcessoResponse> ConsultarNiveisAcessoAsync(SistemaHorarios.Contracts.ConsultarNiveisAcesso.ConsultarNiveisAcessoRequest request) {
            return base.Channel.ConsultarNiveisAcessoAsync(request);
        }
        
        public SistemaHorarios.Contracts.ConsultarDiasPeriodos.ConsultarDiasPeriodosResponse ConsultarDiasPeriodos(SistemaHorarios.Contracts.ConsultarDiasPeriodos.ConsultarDiasPeriodosRequest request) {
            return base.Channel.ConsultarDiasPeriodos(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarDiasPeriodos.ConsultarDiasPeriodosResponse> ConsultarDiasPeriodosAsync(SistemaHorarios.Contracts.ConsultarDiasPeriodos.ConsultarDiasPeriodosRequest request) {
            return base.Channel.ConsultarDiasPeriodosAsync(request);
        }
        
        public SistemaHorarios.Contracts.ConsultarDiasHorarios.ConsultarDiasHorariosResponse ConsultarDiasHorarios(SistemaHorarios.Contracts.ConsultarDiasHorarios.ConsultarDiasHorariosRequest request) {
            return base.Channel.ConsultarDiasHorarios(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarDiasHorarios.ConsultarDiasHorariosResponse> ConsultarDiasHorariosAsync(SistemaHorarios.Contracts.ConsultarDiasHorarios.ConsultarDiasHorariosRequest request) {
            return base.Channel.ConsultarDiasHorariosAsync(request);
        }
        
        public SistemaHorarios.Contracts.ConsultarUsuariosParam.ConsultarUsuariosParamResponse ConsultarUsuariosParam(SistemaHorarios.Contracts.ConsultarUsuariosParam.ConsultarUsuariosParamRequest request) {
            return base.Channel.ConsultarUsuariosParam(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarUsuariosParam.ConsultarUsuariosParamResponse> ConsultarUsuariosParamAsync(SistemaHorarios.Contracts.ConsultarUsuariosParam.ConsultarUsuariosParamRequest request) {
            return base.Channel.ConsultarUsuariosParamAsync(request);
        }
        
        public SistemaHorarios.Contracts.ConsultarUsuariosNiveis.ConsultarUsuariosNiveisResponse ConsultarUsuariosNiveis(SistemaHorarios.Contracts.ConsultarUsuariosNiveis.ConsultarUsuariosNiveisRequest request) {
            return base.Channel.ConsultarUsuariosNiveis(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarUsuariosNiveis.ConsultarUsuariosNiveisResponse> ConsultarUsuariosNiveisAsync(SistemaHorarios.Contracts.ConsultarUsuariosNiveis.ConsultarUsuariosNiveisRequest request) {
            return base.Channel.ConsultarUsuariosNiveisAsync(request);
        }
        
        public SistemaHorarios.Contracts.AutenticarUsuario.AutenticarUsuarioResponse AutenticarUsuario(SistemaHorarios.Contracts.AutenticarUsuario.AutenticarUsuarioRequest request) {
            return base.Channel.AutenticarUsuario(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.AutenticarUsuario.AutenticarUsuarioResponse> AutenticarUsuarioAsync(SistemaHorarios.Contracts.AutenticarUsuario.AutenticarUsuarioRequest request) {
            return base.Channel.AutenticarUsuarioAsync(request);
        }
        
        public SistemaHorarios.Contracts.ConsultarGrade.ConsultarGradeResponse ConsultarGrade(SistemaHorarios.Contracts.ConsultarGrade.ConsultarGradeRequest request) {
            return base.Channel.ConsultarGrade(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarGrade.ConsultarGradeResponse> ConsultarGradeAsync(SistemaHorarios.Contracts.ConsultarGrade.ConsultarGradeRequest request) {
            return base.Channel.ConsultarGradeAsync(request);
        }
        
        public SistemaHorarios.Contracts.ConsultarPeriodosPorCurso.ConsultarPeriodosPorCursoResponse ConsultarPeriodosPorCurso(SistemaHorarios.Contracts.ConsultarPeriodosPorCurso.ConsultarPeriodosPorCursoRequest request) {
            return base.Channel.ConsultarPeriodosPorCurso(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarPeriodosPorCurso.ConsultarPeriodosPorCursoResponse> ConsultarPeriodosPorCursoAsync(SistemaHorarios.Contracts.ConsultarPeriodosPorCurso.ConsultarPeriodosPorCursoRequest request) {
            return base.Channel.ConsultarPeriodosPorCursoAsync(request);
        }
        
        public SistemaHorarios.Contracts.ConsultarCursosSemestres.ConsultarCursosSemestresResponse ConsultarCursosSemestres(SistemaHorarios.Contracts.ConsultarCursosSemestres.ConsultarCursosSemestresRequest request) {
            return base.Channel.ConsultarCursosSemestres(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarCursosSemestres.ConsultarCursosSemestresResponse> ConsultarCursosSemestresAsync(SistemaHorarios.Contracts.ConsultarCursosSemestres.ConsultarCursosSemestresRequest request) {
            return base.Channel.ConsultarCursosSemestresAsync(request);
        }
        
        public SistemaHorarios.Contracts.ConsultarCursosPeriodosSemestres.ConsultarCursosPeriodosSemestresResponse ConsultarCursosPeriodosSemestres(SistemaHorarios.Contracts.ConsultarCursosPeriodosSemestres.ConsultarCursosPeriodosSemestresRequest request) {
            return base.Channel.ConsultarCursosPeriodosSemestres(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarCursosPeriodosSemestres.ConsultarCursosPeriodosSemestresResponse> ConsultarCursosPeriodosSemestresAsync(SistemaHorarios.Contracts.ConsultarCursosPeriodosSemestres.ConsultarCursosPeriodosSemestresRequest request) {
            return base.Channel.ConsultarCursosPeriodosSemestresAsync(request);
        }
        
        public SistemaHorarios.Contracts.ConsultarParametrosCadastroGrade.ConsultarParametrosCadastroGradeResponse ConsultarParametrosCadastroGrade(SistemaHorarios.Contracts.ConsultarParametrosCadastroGrade.ConsultarParametrosCadastroGradeRequest request) {
            return base.Channel.ConsultarParametrosCadastroGrade(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.ConsultarParametrosCadastroGrade.ConsultarParametrosCadastroGradeResponse> ConsultarParametrosCadastroGradeAsync(SistemaHorarios.Contracts.ConsultarParametrosCadastroGrade.ConsultarParametrosCadastroGradeRequest request) {
            return base.Channel.ConsultarParametrosCadastroGradeAsync(request);
        }
        
        public SistemaHorarios.Contracts.CadastrarGrade.CadastrarGradeResponse CadastrarGrade(SistemaHorarios.Contracts.CadastrarGrade.CadastrarGradeRequest request) {
            return base.Channel.CadastrarGrade(request);
        }
        
        public System.Threading.Tasks.Task<SistemaHorarios.Contracts.CadastrarGrade.CadastrarGradeResponse> CadastrarGradeAsync(SistemaHorarios.Contracts.CadastrarGrade.CadastrarGradeRequest request) {
            return base.Channel.CadastrarGradeAsync(request);
        }
    }
}
